development:
  client_id: 12345
  client_secret: abcdef
  redirect_uri: http://localhost:3000
  site: https://api.sandbox.inbloom.org/
  rest_url: api/rest/v1.2/

test:
  client_id: 23456
  client_secret: bcdefg
  redirect_uri: test-server
  site: https://api.sandbox.inbloom.org/
  rest_url: api/rest/v1.2/

  
production:
  client_id: 34567
  client_secret: cdefgh
  redirect_uri: production-server
  site: https://api.sandbox.inbloom.org/
  rest_url: api/rest/v1.2/

